### ISSUE TITLE
Environment Requirements

### ISSUE THREAD

**Issue by Yangziyu** [samyak0210/ViNet#2]
Hi,  I have some problem with the environments, the version of some packages doesn't match. Could you please provide some details about your environment requirements? Thank you very much.

**Comment by samyak0210** [comment]
Hello, I can upload the requirements.txt file but there may be other packages which are not required for this repo. They would be unnecessarily downloaded. If the issue is still not resolved, I will upload it by EOD

**Comment by Yangziyu** [comment]
Thank you so much!
